# Generated by Django 5.1.2 on 2024-10-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_auther_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
